<div class="row">
    <div class="col-md-12">
        @if(count($helps)>0)
            @foreach ($helps as $key=>$help)
                <div class="faq pb-2" id="accordion">
                    <div class="card">
                        <div class="card-header" id="faqHeading-1">
                            <div class="mb-0">
                                <div class="float-right pt-3 pr-3">
                                    {{-- @if ($EDIT_ACCESS) --}}
                                    @php
                                    $username= Helper::user_name($help->request_generated_by);
                                    $company_name =Helper::company_name($help->business_id);
                                    @endphp
                                    <span>Query Generated on:- {{ date('d-m-Y',strtotime($help->created_at))}}</span><br>
                                    <span>Generated By:- {{ $username }} ({{ $company_name }})</span>
                                    {{-- @endif --}}
                                    {{-- @if ($DELETE_ACCESS)
                                    <a href="{{url('faq/delete',['id'=>base64_encode($helps->id)])}}" style="font-size: 16px;" title="delete" onclick="return del()"><i class="fa fa-trash text-danger"></i></a>   
                                    @endif --}}
                                </div>
                                <h5 class="faq-title" data-toggle="collapse" data-target="#faqCollapse-{{$key+1}}" data-aria-expanded="true" data-aria-controls="faqCollapse-1">
                                    <span class="badge">{{$key + 1}}</span> {!! $help->subject !!}
                                </h5>
                            </div>
                        </div>
                        @php
                            $help_response='';
                            $help_response= Helper::get_guest_help_response_data($help->id,$help->business_id);
                        @endphp
                        <div id="faqCollapse-{{$key+1}}" class="collapse" aria-labelledby="faqHeading-1" data-parent="#accordion">
                            <div class="card-body py-2">
                                <label id="answer" style="height: auto;" class="form-control answer" name="answer" placeholder="e.g. Answer" >Subject:- {{ $help->subject }} <br>Comment:- {!! $help->content !!} <br> Response:-{!! $help_response !!}</label>
                            </div>
                            <div  class="float-right pt-3 pr-3">
                                <a href="{{url('app/guest/help/response',['id'=>base64_encode($help->id)])}}" class="btn btn-primay" style="font-size: 16px;" title="Response"><i class="fas fa-phone-volume"></i> Reply</a>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        @else
            <center>
                <img class="emptydata" src="{{asset('guest/images/empty-data.svg')}}"><br>
                <p class="text-muted" style="font-size:17px;"><strong> No Data found</strong></p>
            </center>
        @endif
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-5">
        <div class="dataTables_info" role="status" aria-live="polite"></div>
    </div>
    <div class="col-sm-12 col-md-7">
      <div class=" paging_simple_numbers" >            
          {!! $helps->render() !!}
      </div>
    </div>
 </div>